%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\MATLAB WORK\UDEMY\Frequency Response.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 18-May-2023 10:53:28

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:I17";

% Specify column names and types
opts.VariableNames = ["Vin1", "freq1", "Vo3", "Vo4", "logfreq1", "Vo1Vin1", "logAv3", "Vo2Vin1", "logAv4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
tbl = readtable("C:\MATLAB WORK\UDEMY\Frequency Response.xlsx", opts, "UseExcel", false);

%% Convert to output type
Vin1 = tbl.Vin1;
freq1 = tbl.freq1;
Vo3 = tbl.Vo3;
Vo4 = tbl.Vo4;
logfreq1 = tbl.logfreq1;
Vo1Vin1 = tbl.Vo1Vin1;
logAv3 = tbl.logAv3;
Vo2Vin1 = tbl.Vo2Vin1;
logAv4 = tbl.logAv4;

%% Clear temporary variables
clear opts tbl